# Generated by Django 5.2.3 on 2025-10-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_id', models.CharField(max_length=100, unique=True)),
                ('appliance_name', models.CharField(max_length=255)),
                ('appliance_type', models.CharField(max_length=100)),
                ('power_rating', models.FloatField(help_text='Power rating in watts')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(max_length=100, unique=True)),
                ('building_name', models.CharField(max_length=255)),
                ('building_type', models.CharField(blank=True, max_length=100, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('energy_consumption', models.FloatField(help_text='Energy consumption in kWh')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage', null=True)),
                ('building_id', models.CharField(blank=True, max_length=100, null=True)),
                ('appliance_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'energy_consumption',
                'ordering': ['-timestamp'],
            },
        ),
    ]
